= Asciidoctor Docker Container
:source-highlighter: coderay

== The environment

This Docker image provides:

* Asciidoctor 2.0.10
* Asciidoctor Diagram 2.0.1 with Graphviz integration (supports plantuml and graphiz diagrams)
* Asciidoctor PDF 1.5.0
* Asciidoctor EPUB3 1.5.0.alpha.12
* Asciidoctor Mathematical
* Asciidoctor reveal.js 3.1.0
* AsciiMath
* Source highlighting using Rouge or CodeRay (Pygments not supported in the default Docker image as only Python 3 is available)
* Asciidoctor Confluence

This image uses Alpine Linux 3.11 as base image.

== How to use it
Open this file with the editor, make some changes and click on the `Preview` icon on the top right of this editor.

Just open `My Workspace` panel on the right, and a `New terminal` in `quay-io-sunix-asciidoctor`.


It will be directly mapped with [path]_/projects_ of the container.

Once started, you can use Asciidoctor commands to convert AsciiDoc files you created in the directory mentioned above. You can find several examples below.

* To run Asciidoctor on a basic AsciiDoc file:
+
[source,bash]
----
asciidoctor README.adoc
asciidoctor-pdf README.adoc
asciidoctor-epub3 README.adoc
----

* To run AsciiDoc on an AsciiDoc file that contains diagrams:
+
[source,bash]
----
asciidoctor -r asciidoctor-diagram sample-with-diagram.adoc
asciidoctor-pdf -r asciidoctor-diagram sample-with-diagram.adoc
asciidoctor-epub3 -r asciidoctor-diagram sample-with-diagram.adoc
----

* To use Asciidoctor Confluence:
+
[source, bash]
----
asciidoctor-confluence --host HOSTNAME --spaceKey SPACEKEY --title TITLE --username USER --password PASSWORD sample.adoc
----

* To use Asciidoctor reveal.js with local downloaded reveal.js:

[source,bash]
----
asciidoctor-revealjs sample-slides.adoc
asciidoctor-revealjs -r asciidoctor-diagram sample-slides.adoc
----

* To use Asciidoctor reveal.js with online reveal.js:

[source,bash]
----
asciidoctor-revealjs -a revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0 sample-slides.adoc
asciidoctor-revealjs -a revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0 -r asciidoctor-diagram sample-slides.adoc
----

